disabled_rules:
- empty_count
- trailing_whitespace
- line_length
- unused_closure_parameter
- force_cast
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
opt_in_rules:
- empty_count
- empty_string
switch_case_alignment:
    indented_cases: true # tira a warning do switch
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 210
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
